language: node_js
node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:

    - stage: test
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn --frozen-lockfile
      before_script:
        - yarn run clean:component
        - yarn run build:component
      script:
        - yarn run test:ci

    - stage: deploy
      if: (branch = master) AND (NOT (type IN (pull_request)))
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn --frozen-lockfile
      before_script:
        - yarn run clean
      script:
        - yarn run build
      deploy:
        - yarn run publish
      after_deploy:
        - cd packages/taro-ui-docs/dist
        - git init
        - git add -A
        - git commit -m "Update Document"
        - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:gh-pages

env:
  global:
    - GH_REF: github.com/NervJS/taro-ui.git
